name: newlaundry
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  curved_navigation_bar: ^0.3.2
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  smooth_star_rating: ^1.0.4
  flutter_svg: ^0.17.4
  image_picker: ^0.6.7+7
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_database: ^4.0.0
  google_sign_in: ^4.5.3
  flutter_auth_buttons: ^0.10.0
  geolocator: ^6.0.0+4
  google_maps_flutter: ^0.5.33
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/sheet 1.png
  - assets/sheet 2.png
  - assets/sheet 3.png
  - assets/pin.png
  - assets/logogoogle.png
  - assets/washing-machine.png
  - assets/start.png
  - assets/location.png
  - assets/shop1.png
  - assets/frame.png
  - assets/boy.png
  - assets/clock.png
  - assets/dress.png
  - assets/pants.png
  - assets/polo-shirt.png
  - assets/shorts.png
  - assets/minus.png
  - assets/add.png




  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Bold.ttf
        - asset: fonts/Prompt-Light.ttf
        - asset: fonts/Prompt-Medium.ttf
        - asset: fonts/Prompt-Regular.ttf

